- name: Configure JEA for vScope
  hosts: windows
  tasks:
    ## Configure pre-reqs
    - name: Install required PowerShell modules
      block:
        - name: Install PowerShell modules
          community.windows.win_psmodule:
            name: "{{ item }}"
            state: present
            accept_license: true
          loop:
            - JeaDsc
      rescue:
        - name: Ensure the required NuGet package provider version is installed
          ansible.windows.win_shell: Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force
        - name: Update PowerShellGet Module
          community.windows.win_psmodule:
            name: PowerShellGet
            # accept_license: true
            allow_clobber: true
            state: present
        - name: Install PowerShell modules
          community.windows.win_psmodule:
            name: "{{ item }}"
            state: present
            accept_license: true
          loop:
            - JeaDsc

    ## Configure JEA
    - name: Create PowerShell module folders
      ansible.windows.win_file:
        path: "{{ item }}"
        state: directory
      loop:
        - 'C:\Program Files\WindowsPowerShell\Modules\vScopeJEA'
        - 'C:\Program Files\WindowsPowerShell\Modules\vScopeJEA\RoleCapabilities'

    - name: Copy files
      ansible.windows.win_copy:
        src: "{{ item | win_basename }}"
        dest: "{{ item }}"
      loop:
        - 'C:\Program Files\WindowsPowerShell\Modules\vScopeJEA\RoleCapabilities\vScopeJEA.psrc'
        - 'C:\Program Files\WindowsPowerShell\Modules\vScopeJEA\vScopeJEA.psd1'

    - name: Create empty module file
      ansible.windows.win_file:
        path: 'C:\Program Files\WindowsPowerShell\Modules\vScopeJEA\vScopeJEAFunctions.psm1'
        state: touch

    - name: Apply Windows DSC configuration using JEAMaintenanceEndpoint Module
      ansible.windows.win_dsc:
        resource_name: JeaSessionConfiguration
        Name: vScopeScan
        RoleDefinitions: "@{ 'PNSFLAB\\labsa0001'    = @{ RoleCapabilities = 'vScopeJEA' } }"
        TranscriptDirectory: 'C:\ProgramData\JEAConfiguration\Transcripts'
        Ensure: Present
        RunAsVirtualAccount: true
      ignore_errors: true # This play will restart WinRM if successful. Ansible will then lose connection
